name: Terraform Fmt Check

on:
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Terraformのバージョンを指定します（適宜変更）

      - name: Run terraform fmt
        run: terraform fmt -check -recursive
